export const Colors = {
  background: '#FAFAF8',
  surface: '#FFFFFF',
  surfaceAlt: '#F4F2EF',
  border: '#E8E4DF',
  text: '#1A1714',
  textSecondary: '#7A746E',
  textTertiary: '#B0A89F',
  accent: '#B5A99A',
  accentDark: '#8C7F72',
  overdue: '#C97B5A',
  overdueLight: '#FBF0EB',
  dueSoon: '#C9A85A',
  dueSoonLight: '#FBF6EB',
  ok: '#6A9E7F',
  okLight: '#EBF5EF',
  tabBar: '#FFFFFF',
  tabBarBorder: '#E8E4DF',
};
